# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=1G
#$ -cwd
#$ -j y
#$ -N fastqc-cael
#$ -o fastqc-cael.log
#
# ----------------Modules------------------------- #
module load bioinformatics/fastqc
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
#
fastqc ./Camptosema_ellipticum_forward_paired.fq.gz \

fastqc ./Camptosema_ellipticum_reverse_paired.fq.gz \
#
echo = `date` job $JOB_NAME done
