# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 48
#$ -q sThC.q
#$ -l mres=2G,h_data=2G,h_vmem=2G
#$ -cwd
#$ -j y
#$ -N trim-cael-new
#$ -o trim-cael-new.log
#
# ----------------Modules------------------------- #
module load bioinformatics/trimmomatic
#
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
runtrimmomatic PE -threads $NSLOTS \
Camptosema_ellipticum_R1.fastq.gz Camptosema_ellipticum_R2.fastq.gz \
Camptosema_ellipticum_R1_forward_paired.fq.gz Camptosema_ellipticum_R1_forward_unpaired.fq.gz \
Camptosema_ellipticum_R2_reverse_paired.fq.gz Camptosema_ellipticum_R2_reverse_unpaired.fq.gz \
ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:5 TRAILING:15 SLIDINGWINDOW:4:15 MINLEN:36
#
echo = `date` job $JOB_NAME done
